//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCatchException.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatchMe_Filter
    {
        public long Codefilter { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string Program { get; set; }
        public string ProcessName { get; set; }
        public string ComputerName { get; set; }
        public int CodeAction { get; set; }
    }
}
