//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCatchException.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatchMe_Exception
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatchMe_Exception()
        {
            this.CatchMe_Exception_Detail = new HashSet<CatchMe_Exception_Detail>();
            this.CatchMe_Exception_Variable = new HashSet<CatchMe_Exception_Variable>();
            this.CatchMe_Exception_Detail_Data = new HashSet<CatchMe_Exception_Detail_Data>();
            this.CatchMe_Exception_Screen = new HashSet<CatchMe_Exception_Screen>();
        }
    
        public long CodeCatch { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<short> UrgenceLevel { get; set; }
        public string Method { get; set; }
        public string sourceFilePath { get; set; }
        public int sourceLineNumber { get; set; }
        public string CurrentPath { get; set; }
        public string ProcessName { get; set; }
        public string ComputerName { get; set; }
        public string OsVersion { get; set; }
        public string OsServicePack { get; set; }
        public string OsPlatform { get; set; }
        public string Login { get; set; }
        public byte[] SID { get; set; }
        public string Program { get; set; }
        public string Version { get; set; }
        public string Path { get; set; }
        public Nullable<bool> Masquer { get; set; }
        public bool Debug { get; set; }
        public byte CodeStatus { get; set; }
        public string LoginStatus { get; set; }
        public Nullable<System.DateTime> DateStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatchMe_Exception_Detail> CatchMe_Exception_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatchMe_Exception_Variable> CatchMe_Exception_Variable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatchMe_Exception_Detail_Data> CatchMe_Exception_Detail_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatchMe_Exception_Screen> CatchMe_Exception_Screen { get; set; }
        public virtual CatchMe_Status CatchMe_Status { get; set; }
    }
}
