//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCatchException.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatchMe_Status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatchMe_Status()
        {
            this.CatchMe_Exception = new HashSet<CatchMe_Exception>();
        }
    
        public byte CodeStatus { get; set; }
        public string Libelle { get; set; }
        public string Suivant { get; set; }
        public int Order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatchMe_Exception> CatchMe_Exception { get; set; }
    }
}
