//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCatchException.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatchMe_Exception_Detail> CatchMe_Exception_Detail { get; set; }
        public virtual DbSet<CatchMe_Exception_Variable> CatchMe_Exception_Variable { get; set; }
        public virtual DbSet<CatchMe_Filter> CatchMe_Filter { get; set; }
        public virtual DbSet<CatchMe_Exception> CatchMe_Exception { get; set; }
        public virtual DbSet<CatchMe_Exception_Detail_Data> CatchMe_Exception_Detail_Data { get; set; }
        public virtual DbSet<CatchMe_Exception_Screen> CatchMe_Exception_Screen { get; set; }
        public virtual DbSet<CatchMe_Status> CatchMe_Status { get; set; }
        public virtual DbSet<CatchMe_ParamMail> CatchMe_ParamMail { get; set; }
    }
}
