//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCatchException.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatchMe_Exception_Screen
    {
        public System.Guid FileKey { get; set; }
        public long CodeCatch { get; set; }
        public byte[] Screen { get; set; }
        public string Ext { get; set; }
        public string Mime { get; set; }
    
        public virtual CatchMe_Exception CatchMe_Exception { get; set; }
    }
}
