//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatchException.mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public string Ordinateur { get; set; }
        public int ApplicationID { get; set; }
        public System.DateTime Date { get; set; }
        public byte[] Exception { get; set; }
        public int DataType { get; set; }
        public bool Hide { get; set; }
    }
}
